### ISSUE TITLE
Create Wiki for Team Kick

### ISSUE THREAD

**Issue by HannanSolo** [david-fisher/320-S22-Track1#5]
Create a page for your team in the wiki section on GitHub. Your page should include your team name, your team member's name, role, and GitHub ID.

**Comment by mvbarba** [comment]
@rnpatel99 @MostafaK2 @maggiekenz @NvLong01 @megk105 can you confirm info on wiki is correct? Can close issue after that.

**Comment by mvbarba** [comment]
https://github.com/david-fisher/320-S22-Track1/wiki/Team-Kick

**Comment by maggiekenz** [comment]
Looks good to me

**Comment by rnpatel99** [comment]
Looks good.
